version: "3.7"
services:
  db:
    image: postgres
    container_name: postgres
    command: -p 5435
    expose:
      - 5435
    ports:
      - 5435:5435
    env_file:
      - .env-non-dev

  redis:
    image: redis
    container_name: redis
    command: --port 5370
    expose:
      - 5370

  fastapi_app:
    build: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:80
    depends_on:
      - db
      - redis

  celery:
    build: .
    env_file:
      - .env-non-dev
    container_name: celery_app
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis

  flower:
    build: .
    env_file:
      - .env-non-dev
    container_name: flower_app
    command: [ "/fastapi_app/docker/celery.sh", "flower" ]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555
